# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.document_yaml_document_read import DocumentYamlDocumentRead

class TestDocumentYamlDocumentRead(unittest.TestCase):
    """DocumentYamlDocumentRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentYamlDocumentRead:
        """Test DocumentYamlDocumentRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentYamlDocumentRead`
        """
        model = DocumentYamlDocumentRead()
        if include_optional:
            return DocumentYamlDocumentRead(
                id = '',
                member = 'https://example.com/',
                url = '',
                type = 'passport',
                uploaded_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                verified = True,
                verified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return DocumentYamlDocumentRead(
                url = '',
                type = 'passport',
        )
        """

    def testDocumentYamlDocumentRead(self):
        """Test DocumentYamlDocumentRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
