# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.api.rsvps_api import RsvpsApi


class TestRsvpsApi(unittest.TestCase):
    """RsvpsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RsvpsApi()

    def tearDown(self) -> None:
        pass

    def test_api_rsvps_get_collection(self) -> None:
        """Test case for api_rsvps_get_collection

        Retrieves the collection of rsvps resources.
        """
        pass

    def test_api_rsvps_id_delete(self) -> None:
        """Test case for api_rsvps_id_delete

        Removes the rsvps resource.
        """
        pass

    def test_api_rsvps_id_get(self) -> None:
        """Test case for api_rsvps_id_get

        Retrieves a rsvps resource.
        """
        pass

    def test_api_rsvps_id_put(self) -> None:
        """Test case for api_rsvps_id_put

        Replaces the rsvps resource.
        """
        pass

    def test_api_rsvps_post(self) -> None:
        """Test case for api_rsvps_post

        Creates a rsvps resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
