# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.api.hello_asso_webhook_dto_api import HelloAssoWebhookDTOApi


class TestHelloAssoWebhookDTOApi(unittest.TestCase):
    """HelloAssoWebhookDTOApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HelloAssoWebhookDTOApi()

    def tearDown(self) -> None:
        pass

    def test_api_hello_assowebhook_post(self) -> None:
        """Test case for api_hello_assowebhook_post

        Creates a HelloAssoWebhookDTO resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
