# coding: utf-8

"""
    GEC API

    Backend API for the GEC (Gestion des Étudiants Congolais) non-profit management application. Provides endpoints for managing members, events, tasks, donations, and communications.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.task_write import TaskWrite

class TestTaskWrite(unittest.TestCase):
    """TaskWrite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskWrite:
        """Test TaskWrite
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskWrite`
        """
        model = TaskWrite()
        if include_optional:
            return TaskWrite(
                title = '',
                description = '',
                status = 'pending',
                assignee = 'https://example.com/',
                due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                priority = 'low',
                related_event = 'https://example.com/',
                related_member = 'https://example.com/'
            )
        else:
            return TaskWrite(
                title = '',
        )
        """

    def testTaskWrite(self):
        """Test TaskWrite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
