# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.rsvps_jsonld_rsvp_read import RsvpsJsonldRsvpRead

class TestRsvpsJsonldRsvpRead(unittest.TestCase):
    """RsvpsJsonldRsvpRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RsvpsJsonldRsvpRead:
        """Test RsvpsJsonldRsvpRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RsvpsJsonldRsvpRead`
        """
        model = RsvpsJsonldRsvpRead()
        if include_optional:
            return RsvpsJsonldRsvpRead(
                context = None,
                id = '',
                type = '',
                id = '',
                event = 'https://example.com/',
                member = 'https://example.com/',
                status = 'attending',
                notes = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return RsvpsJsonldRsvpRead(
                event = 'https://example.com/',
                member = 'https://example.com/',
                status = 'attending',
        )
        """

    def testRsvpsJsonldRsvpRead(self):
        """Test RsvpsJsonldRsvpRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
