# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.hello_asso_amount_dto import HelloAssoAmountDTO

class TestHelloAssoAmountDTO(unittest.TestCase):
    """HelloAssoAmountDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HelloAssoAmountDTO:
        """Test HelloAssoAmountDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HelloAssoAmountDTO`
        """
        model = HelloAssoAmountDTO()
        if include_optional:
            return HelloAssoAmountDTO(
                total = 0,
                vat = 0,
                discount = 0
            )
        else:
            return HelloAssoAmountDTO(
                total = 0,
                vat = 0,
                discount = 0,
        )
        """

    def testHelloAssoAmountDTO(self):
        """Test HelloAssoAmountDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
