# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.user_user_write_json_merge_patch import UserUserWriteJsonMergePatch

class TestUserUserWriteJsonMergePatch(unittest.TestCase):
    """UserUserWriteJsonMergePatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserUserWriteJsonMergePatch:
        """Test UserUserWriteJsonMergePatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserUserWriteJsonMergePatch`
        """
        model = UserUserWriteJsonMergePatch()
        if include_optional:
            return UserUserWriteJsonMergePatch(
                email = '',
                plain_password = '',
                roles = [
                    ''
                    ],
                google_service_account = '',
                google_service_account_scopes = [
                    ''
                    ],
                google_impersonated_user = ''
            )
        else:
            return UserUserWriteJsonMergePatch(
        )
        """

    def testUserUserWriteJsonMergePatch(self):
        """Test UserUserWriteJsonMergePatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
