# coding: utf-8

"""
    GEC API

    Backend API for the GEC (Gestion des Étudiants Congolais) non-profit management application. Provides endpoints for managing members, events, tasks, donations, and communications.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.api.rsvp_api import RsvpApi


class TestRsvpApi(unittest.TestCase):
    """RsvpApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RsvpApi()

    def tearDown(self) -> None:
        pass

    def test_create_rsvp(self) -> None:
        """Test case for create_rsvp

        Creates a Rsvp resource.
        """
        pass

    def test_delete_rsvp(self) -> None:
        """Test case for delete_rsvp

        Removes the Rsvp resource.
        """
        pass

    def test_list_rsvps(self) -> None:
        """Test case for list_rsvps

        Retrieves the collection of Rsvp resources.
        """
        pass

    def test_update_rsvp(self) -> None:
        """Test case for update_rsvp

        Replaces the Rsvp resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
