# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.api.task_api import TaskApi


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TaskApi()

    def tearDown(self) -> None:
        pass

    def test_api_tasks_get_collection(self) -> None:
        """Test case for api_tasks_get_collection

        Retrieves the collection of Task resources.
        """
        pass

    def test_api_tasks_id_delete(self) -> None:
        """Test case for api_tasks_id_delete

        Removes the Task resource.
        """
        pass

    def test_api_tasks_id_get(self) -> None:
        """Test case for api_tasks_id_get

        Retrieves a Task resource.
        """
        pass

    def test_api_tasks_id_put(self) -> None:
        """Test case for api_tasks_id_put

        Replaces the Task resource.
        """
        pass

    def test_api_tasks_post(self) -> None:
        """Test case for api_tasks_post

        Creates a Task resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
