# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.wif_credential_token_response_dto import WifCredentialTokenResponseDTO

class TestWifCredentialTokenResponseDTO(unittest.TestCase):
    """WifCredentialTokenResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WifCredentialTokenResponseDTO:
        """Test WifCredentialTokenResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WifCredentialTokenResponseDTO`
        """
        model = WifCredentialTokenResponseDTO()
        if include_optional:
            return WifCredentialTokenResponseDTO(
                version = 56,
                success = True,
                token_type = '',
                expires_in = 56,
                expiration_time = 56,
                access_token = ''
            )
        else:
            return WifCredentialTokenResponseDTO(
        )
        """

    def testWifCredentialTokenResponseDTO(self):
        """Test WifCredentialTokenResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
