# coding: utf-8

"""
    GEC API

    Backend API for the GEC (Gestion des Étudiants Congolais) non-profit management application. Provides endpoints for managing members, events, tasks, donations, and communications.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.email_template_write import EmailTemplateWrite

class TestEmailTemplateWrite(unittest.TestCase):
    """EmailTemplateWrite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmailTemplateWrite:
        """Test EmailTemplateWrite
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmailTemplateWrite`
        """
        model = EmailTemplateWrite()
        if include_optional:
            return EmailTemplateWrite(
                name = '',
                subject = '',
                content = '',
                variables = [
                    ''
                    ]
            )
        else:
            return EmailTemplateWrite(
                name = '',
                subject = '',
                content = '',
        )
        """

    def testEmailTemplateWrite(self):
        """Test EmailTemplateWrite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
