# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.login_check_post200_response import LoginCheckPost200Response

class TestLoginCheckPost200Response(unittest.TestCase):
    """LoginCheckPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoginCheckPost200Response:
        """Test LoginCheckPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoginCheckPost200Response`
        """
        model = LoginCheckPost200Response()
        if include_optional:
            return LoginCheckPost200Response(
                token = ''
            )
        else:
            return LoginCheckPost200Response(
                token = '',
        )
        """

    def testLoginCheckPost200Response(self):
        """Test LoginCheckPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
