# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.constraint_violation import ConstraintViolation

class TestConstraintViolation(unittest.TestCase):
    """ConstraintViolation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConstraintViolation:
        """Test ConstraintViolation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConstraintViolation`
        """
        model = ConstraintViolation()
        if include_optional:
            return ConstraintViolation(
                status = 56,
                violations = [
                    gec_api_sdk.models.constraint_violation_violations_inner.ConstraintViolation_violations_inner(
                        property_path = '', 
                        message = '', 
                        code = '', 
                        hint = '', 
                        payload = { }, )
                    ],
                detail = '',
                type = '',
                title = '',
                instance = ''
            )
        else:
            return ConstraintViolation(
        )
        """

    def testConstraintViolation(self):
        """Test ConstraintViolation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
