# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.api_rsvps_get_collection200_response import ApiRsvpsGetCollection200Response

class TestApiRsvpsGetCollection200Response(unittest.TestCase):
    """ApiRsvpsGetCollection200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiRsvpsGetCollection200Response:
        """Test ApiRsvpsGetCollection200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiRsvpsGetCollection200Response`
        """
        model = ApiRsvpsGetCollection200Response()
        if include_optional:
            return ApiRsvpsGetCollection200Response(
                member = [
                    gec_api_sdk.models.rsvps/jsonld_rsvp/read.rsvps.jsonld-rsvp.read(
                        @context = null, 
                        @id = '', 
                        @type = '', 
                        id = '', 
                        event = 'https://example.com/', 
                        member = 'https://example.com/', 
                        status = 'attending', 
                        notes = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total_items = 0,
                view = {"@id":"string","type":"string","first":"string","last":"string","previous":"string","next":"string"},
                search = gec_api_sdk.models.api_documents_get_collection_200_response_search.api_documents_get_collection_200_response_search(
                    @type = '', 
                    template = '', 
                    variable_representation = '', 
                    mapping = [
                        gec_api_sdk.models.api_documents_get_collection_200_response_search_mapping_inner.api_documents_get_collection_200_response_search_mapping_inner(
                            @type = '', 
                            variable = '', 
                            property = '', 
                            required = True, )
                        ], )
            )
        else:
            return ApiRsvpsGetCollection200Response(
                member = [
                    gec_api_sdk.models.rsvps/jsonld_rsvp/read.rsvps.jsonld-rsvp.read(
                        @context = null, 
                        @id = '', 
                        @type = '', 
                        id = '', 
                        event = 'https://example.com/', 
                        member = 'https://example.com/', 
                        status = 'attending', 
                        notes = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testApiRsvpsGetCollection200Response(self):
        """Test ApiRsvpsGetCollection200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
