# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.wif_credential_token_response_dto_wif_credential_token_request_dto import WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO

class TestWifCredentialTokenResponseDTOWifCredentialTokenRequestDTO(unittest.TestCase):
    """WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO:
        """Test WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO`
        """
        model = WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO()
        if include_optional:
            return WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO(
                user_email = '',
                service_account = '',
                ttl = 56
            )
        else:
            return WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO(
        )
        """

    def testWifCredentialTokenResponseDTOWifCredentialTokenRequestDTO(self):
        """Test WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
