# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.hydra_item_base_schema_context_one_of import HydraItemBaseSchemaContextOneOf

class TestHydraItemBaseSchemaContextOneOf(unittest.TestCase):
    """HydraItemBaseSchemaContextOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HydraItemBaseSchemaContextOneOf:
        """Test HydraItemBaseSchemaContextOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HydraItemBaseSchemaContextOneOf`
        """
        model = HydraItemBaseSchemaContextOneOf()
        if include_optional:
            return HydraItemBaseSchemaContextOneOf(
                vocab = '',
                hydra = 'http://www.w3.org/ns/hydra/core#'
            )
        else:
            return HydraItemBaseSchemaContextOneOf(
                vocab = '',
                hydra = 'http://www.w3.org/ns/hydra/core#',
        )
        """

    def testHydraItemBaseSchemaContextOneOf(self):
        """Test HydraItemBaseSchemaContextOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
