# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.rsvps_yaml_rsvp_read import RsvpsYamlRsvpRead

class TestRsvpsYamlRsvpRead(unittest.TestCase):
    """RsvpsYamlRsvpRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RsvpsYamlRsvpRead:
        """Test RsvpsYamlRsvpRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RsvpsYamlRsvpRead`
        """
        model = RsvpsYamlRsvpRead()
        if include_optional:
            return RsvpsYamlRsvpRead(
                id = '',
                event = 'https://example.com/',
                member = 'https://example.com/',
                status = 'attending',
                notes = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return RsvpsYamlRsvpRead(
                event = 'https://example.com/',
                member = 'https://example.com/',
                status = 'attending',
        )
        """

    def testRsvpsYamlRsvpRead(self):
        """Test RsvpsYamlRsvpRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
