# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.api.wif_credential_token_response_dto_api import WifCredentialTokenResponseDTOApi


class TestWifCredentialTokenResponseDTOApi(unittest.TestCase):
    """WifCredentialTokenResponseDTOApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WifCredentialTokenResponseDTOApi()

    def tearDown(self) -> None:
        pass

    def test_api_internalwifcredential_token_get(self) -> None:
        """Test case for api_internalwifcredential_token_get

        Retrieves a WifCredentialTokenResponseDTO resource.
        """
        pass

    def test_api_internalwifcredential_token_post(self) -> None:
        """Test case for api_internalwifcredential_token_post

        Creates a WifCredentialTokenResponseDTO resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
