# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.hydra_collection_base_schema_no_pagination_search_mapping_inner import HydraCollectionBaseSchemaNoPaginationSearchMappingInner

class TestHydraCollectionBaseSchemaNoPaginationSearchMappingInner(unittest.TestCase):
    """HydraCollectionBaseSchemaNoPaginationSearchMappingInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HydraCollectionBaseSchemaNoPaginationSearchMappingInner:
        """Test HydraCollectionBaseSchemaNoPaginationSearchMappingInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HydraCollectionBaseSchemaNoPaginationSearchMappingInner`
        """
        model = HydraCollectionBaseSchemaNoPaginationSearchMappingInner()
        if include_optional:
            return HydraCollectionBaseSchemaNoPaginationSearchMappingInner(
                type = '',
                variable = '',
                var_property = '',
                required = True
            )
        else:
            return HydraCollectionBaseSchemaNoPaginationSearchMappingInner(
        )
        """

    def testHydraCollectionBaseSchemaNoPaginationSearchMappingInner(self):
        """Test HydraCollectionBaseSchemaNoPaginationSearchMappingInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
