# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.api_events_get_collection200_response import ApiEventsGetCollection200Response

class TestApiEventsGetCollection200Response(unittest.TestCase):
    """ApiEventsGetCollection200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiEventsGetCollection200Response:
        """Test ApiEventsGetCollection200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiEventsGetCollection200Response`
        """
        model = ApiEventsGetCollection200Response()
        if include_optional:
            return ApiEventsGetCollection200Response(
                member = [
                    gec_api_sdk.models.event/jsonld_event/read.Event.jsonld-event.read(
                        @context = null, 
                        @id = '', 
                        @type = '', 
                        id = '', 
                        title = '', 
                        description = '', 
                        start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        location = '', 
                        max_attendees = 0, 
                        current_attendees = 0, 
                        status = 'draft', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        rsvps = [
                            'https://example.com/'
                            ], 
                        tasks = [
                            'https://example.com/'
                            ], )
                    ],
                total_items = 0,
                view = {"@id":"string","type":"string","first":"string","last":"string","previous":"string","next":"string"},
                search = gec_api_sdk.models.api_documents_get_collection_200_response_search.api_documents_get_collection_200_response_search(
                    @type = '', 
                    template = '', 
                    variable_representation = '', 
                    mapping = [
                        gec_api_sdk.models.api_documents_get_collection_200_response_search_mapping_inner.api_documents_get_collection_200_response_search_mapping_inner(
                            @type = '', 
                            variable = '', 
                            property = '', 
                            required = True, )
                        ], )
            )
        else:
            return ApiEventsGetCollection200Response(
                member = [
                    gec_api_sdk.models.event/jsonld_event/read.Event.jsonld-event.read(
                        @context = null, 
                        @id = '', 
                        @type = '', 
                        id = '', 
                        title = '', 
                        description = '', 
                        start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        location = '', 
                        max_attendees = 0, 
                        current_attendees = 0, 
                        status = 'draft', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        rsvps = [
                            'https://example.com/'
                            ], 
                        tasks = [
                            'https://example.com/'
                            ], )
                    ],
        )
        """

    def testApiEventsGetCollection200Response(self):
        """Test ApiEventsGetCollection200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
