# coding: utf-8

"""
    GEC API

    Backend API for the GEC (Gestion des Étudiants Congolais) non-profit management application. Provides endpoints for managing members, events, tasks, donations, and communications.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.user_write import UserWrite

class TestUserWrite(unittest.TestCase):
    """UserWrite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserWrite:
        """Test UserWrite
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserWrite`
        """
        model = UserWrite()
        if include_optional:
            return UserWrite(
                email = '',
                plain_password = '',
                roles = [
                    ''
                    ],
                google_service_account = '',
                google_service_account_scopes = [
                    ''
                    ],
                google_impersonated_user = ''
            )
        else:
            return UserWrite(
                email = '',
                plain_password = '',
        )
        """

    def testUserWrite(self):
        """Test UserWrite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
