# coding: utf-8

"""
    GEC API

    Backend API for the GEC (Gestion des Étudiants Congolais) non-profit management application. Provides endpoints for managing members, events, tasks, donations, and communications.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.rsvp_write import RsvpWrite

class TestRsvpWrite(unittest.TestCase):
    """RsvpWrite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RsvpWrite:
        """Test RsvpWrite
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RsvpWrite`
        """
        model = RsvpWrite()
        if include_optional:
            return RsvpWrite(
                event = 'https://example.com/',
                member = 'https://example.com/',
                status = 'attending',
                notes = ''
            )
        else:
            return RsvpWrite(
                event = 'https://example.com/',
                member = 'https://example.com/',
                status = 'attending',
        )
        """

    def testRsvpWrite(self):
        """Test RsvpWrite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
