# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.api_members_get_collection200_response import ApiMembersGetCollection200Response

class TestApiMembersGetCollection200Response(unittest.TestCase):
    """ApiMembersGetCollection200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiMembersGetCollection200Response:
        """Test ApiMembersGetCollection200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiMembersGetCollection200Response`
        """
        model = ApiMembersGetCollection200Response()
        if include_optional:
            return ApiMembersGetCollection200Response(
                member = [
                    gec_api_sdk.models.member/jsonld_member/read.Member.jsonld-member.read(
                        @context = null, 
                        @id = '', 
                        @type = '', 
                        id = '', 
                        first_name = '', 
                        last_name = '', 
                        email = '', 
                        birth_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        gender = 'male', 
                        phone_number_fr = '', 
                        phone_number_cg = '', 
                        postal_address = '', 
                        postal_code = '', 
                        city = '', 
                        first_year = True, 
                        formation = '', 
                        establishment = '', 
                        study_level = '', 
                        training_cycle = '', 
                        other_associations = True, 
                        association_names = '', 
                        has_passport_cg = True, 
                        has_visa = True, 
                        has_school_certificate = True, 
                        photo_url = '', 
                        status = 'active', 
                        membership_type = 'student', 
                        contribution = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        documents = [
                            'https://example.com/'
                            ], 
                        rsvps = [
                            'https://example.com/'
                            ], 
                        donations = [
                            'https://example.com/'
                            ], )
                    ],
                total_items = 0,
                view = {"@id":"string","type":"string","first":"string","last":"string","previous":"string","next":"string"},
                search = gec_api_sdk.models.api_documents_get_collection_200_response_search.api_documents_get_collection_200_response_search(
                    @type = '', 
                    template = '', 
                    variable_representation = '', 
                    mapping = [
                        gec_api_sdk.models.api_documents_get_collection_200_response_search_mapping_inner.api_documents_get_collection_200_response_search_mapping_inner(
                            @type = '', 
                            variable = '', 
                            property = '', 
                            required = True, )
                        ], )
            )
        else:
            return ApiMembersGetCollection200Response(
                member = [
                    gec_api_sdk.models.member/jsonld_member/read.Member.jsonld-member.read(
                        @context = null, 
                        @id = '', 
                        @type = '', 
                        id = '', 
                        first_name = '', 
                        last_name = '', 
                        email = '', 
                        birth_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        gender = 'male', 
                        phone_number_fr = '', 
                        phone_number_cg = '', 
                        postal_address = '', 
                        postal_code = '', 
                        city = '', 
                        first_year = True, 
                        formation = '', 
                        establishment = '', 
                        study_level = '', 
                        training_cycle = '', 
                        other_associations = True, 
                        association_names = '', 
                        has_passport_cg = True, 
                        has_visa = True, 
                        has_school_certificate = True, 
                        photo_url = '', 
                        status = 'active', 
                        membership_type = 'student', 
                        contribution = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        documents = [
                            'https://example.com/'
                            ], 
                        rsvps = [
                            'https://example.com/'
                            ], 
                        donations = [
                            'https://example.com/'
                            ], )
                    ],
        )
        """

    def testApiMembersGetCollection200Response(self):
        """Test ApiMembersGetCollection200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
