# coding: utf-8

"""
    GEC API

    Backend API for the GEC (Gestion des Étudiants Congolais) non-profit management application. Provides endpoints for managing members, events, tasks, donations, and communications.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.member_read import MemberRead

class TestMemberRead(unittest.TestCase):
    """MemberRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MemberRead:
        """Test MemberRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MemberRead`
        """
        model = MemberRead()
        if include_optional:
            return MemberRead(
                id = '',
                first_name = '',
                last_name = '',
                email = '',
                birth_date = '2000-01-15',
                gender = 'male',
                phone_number_fr = '',
                phone_number_cg = '',
                postal_address = '',
                postal_code = '',
                city = '',
                is_first_year_study = True,
                first_year = '2023-09-01',
                formation = '',
                establishment = '',
                study_level = '',
                training_cycle = 'initial',
                other_associations = True,
                association_names = '',
                has_passport_cg = True,
                has_visa = True,
                has_school_certificate = True,
                photo_url = '',
                status = 'active',
                membership_type = 'student',
                membership_start_date = '2024-10-01',
                contribution = 1.337,
                contribution_status = 'paid',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                documents = [
                    'https://example.com/'
                    ],
                rsvps = [
                    'https://example.com/'
                    ],
                donations = [
                    'https://example.com/'
                    ]
            )
        else:
            return MemberRead(
                first_name = '',
                last_name = '',
                status = 'active',
                membership_type = 'student',
        )
        """

    def testMemberRead(self):
        """Test MemberRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
