# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.error_jsonld import ErrorJsonld

class TestErrorJsonld(unittest.TestCase):
    """ErrorJsonld unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorJsonld:
        """Test ErrorJsonld
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorJsonld`
        """
        model = ErrorJsonld()
        if include_optional:
            return ErrorJsonld(
                context = None,
                id = '',
                type = '',
                title = '',
                detail = '',
                status = 1.337,
                instance = '',
                type = '',
                description = ''
            )
        else:
            return ErrorJsonld(
        )
        """

    def testErrorJsonld(self):
        """Test ErrorJsonld"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
