# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.donation_jsonld_donation_write import DonationJsonldDonationWrite

class TestDonationJsonldDonationWrite(unittest.TestCase):
    """DonationJsonldDonationWrite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DonationJsonldDonationWrite:
        """Test DonationJsonldDonationWrite
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DonationJsonldDonationWrite`
        """
        model = DonationJsonldDonationWrite()
        if include_optional:
            return DonationJsonldDonationWrite(
                member = 'https://example.com/',
                amount = '',
                currency = 'EUR',
                status = 'pending',
                payment_method = 'card',
                notes = ''
            )
        else:
            return DonationJsonldDonationWrite(
                amount = '',
        )
        """

    def testDonationJsonldDonationWrite(self):
        """Test DonationJsonldDonationWrite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
