# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.api.event_api import EventApi


class TestEventApi(unittest.TestCase):
    """EventApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventApi()

    def tearDown(self) -> None:
        pass

    def test_api_events_get_collection(self) -> None:
        """Test case for api_events_get_collection

        Retrieves the collection of Event resources.
        """
        pass

    def test_api_events_id_delete(self) -> None:
        """Test case for api_events_id_delete

        Removes the Event resource.
        """
        pass

    def test_api_events_id_get(self) -> None:
        """Test case for api_events_id_get

        Retrieves a Event resource.
        """
        pass

    def test_api_events_id_put(self) -> None:
        """Test case for api_events_id_put

        Replaces the Event resource.
        """
        pass

    def test_api_events_post(self) -> None:
        """Test case for api_events_post

        Creates a Event resource.
        """
        pass


if __name__ == '__main__':
    unittest.main()
