# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.event_jsonld_event_write import EventJsonldEventWrite

class TestEventJsonldEventWrite(unittest.TestCase):
    """EventJsonldEventWrite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventJsonldEventWrite:
        """Test EventJsonldEventWrite
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventJsonldEventWrite`
        """
        model = EventJsonldEventWrite()
        if include_optional:
            return EventJsonldEventWrite(
                title = '',
                description = '',
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                location = '',
                max_attendees = 0,
                status = 'draft'
            )
        else:
            return EventJsonldEventWrite(
                title = '',
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testEventJsonldEventWrite(self):
        """Test EventJsonldEventWrite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
