# coding: utf-8

"""
    GEC API

    Backend API for the GEC (Gestion des Étudiants Congolais) non-profit management application. Provides endpoints for managing members, events, tasks, donations, and communications.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.api.hello_asso_webhooks_api import HelloAssoWebhooksApi


class TestHelloAssoWebhooksApi(unittest.TestCase):
    """HelloAssoWebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HelloAssoWebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_api_hello_assowebhook_post(self) -> None:
        """Test case for api_hello_assowebhook_post

        Receive HelloAsso webhook notifications
        """
        pass


if __name__ == '__main__':
    unittest.main()
