# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.hydra_collection_base_schema import HydraCollectionBaseSchema

class TestHydraCollectionBaseSchema(unittest.TestCase):
    """HydraCollectionBaseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HydraCollectionBaseSchema:
        """Test HydraCollectionBaseSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HydraCollectionBaseSchema`
        """
        model = HydraCollectionBaseSchema()
        if include_optional:
            return HydraCollectionBaseSchema(
                total_items = 0,
                search = gec_api_sdk.models.hydra_collection_base_schema_no_pagination_search.HydraCollectionBaseSchemaNoPagination_search(
                    @type = '', 
                    template = '', 
                    variable_representation = '', 
                    mapping = [
                        gec_api_sdk.models.hydra_collection_base_schema_no_pagination_search_mapping_inner.HydraCollectionBaseSchemaNoPagination_search_mapping_inner(
                            @type = '', 
                            variable = '', 
                            property = '', 
                            required = True, )
                        ], ),
                view = {@id=string, type=string, first=string, last=string, previous=string, next=string}
            )
        else:
            return HydraCollectionBaseSchema(
        )
        """

    def testHydraCollectionBaseSchema(self):
        """Test HydraCollectionBaseSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
