# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.api_documents_get_collection200_response_search_mapping_inner import ApiDocumentsGetCollection200ResponseSearchMappingInner

class TestApiDocumentsGetCollection200ResponseSearchMappingInner(unittest.TestCase):
    """ApiDocumentsGetCollection200ResponseSearchMappingInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiDocumentsGetCollection200ResponseSearchMappingInner:
        """Test ApiDocumentsGetCollection200ResponseSearchMappingInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiDocumentsGetCollection200ResponseSearchMappingInner`
        """
        model = ApiDocumentsGetCollection200ResponseSearchMappingInner()
        if include_optional:
            return ApiDocumentsGetCollection200ResponseSearchMappingInner(
                type = '',
                variable = '',
                var_property = '',
                required = True
            )
        else:
            return ApiDocumentsGetCollection200ResponseSearchMappingInner(
        )
        """

    def testApiDocumentsGetCollection200ResponseSearchMappingInner(self):
        """Test ApiDocumentsGetCollection200ResponseSearchMappingInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
