# coding: utf-8

"""
    GEC API

    Backend API for the GEC (Gestion des Étudiants Congolais) non-profit management application. Provides endpoints for managing members, events, tasks, donations, and communications.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gec_api_sdk.models.education_write import EducationWrite

class TestEducationWrite(unittest.TestCase):
    """EducationWrite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EducationWrite:
        """Test EducationWrite
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EducationWrite`
        """
        model = EducationWrite()
        if include_optional:
            return EducationWrite(
                is_first_year_study = True,
                first_year = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                formation = '',
                establishment = '',
                study_level = '',
                training_cycle = 'initial'
            )
        else:
            return EducationWrite(
        )
        """

    def testEducationWrite(self):
        """Test EducationWrite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
