# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from gec_api_sdk.models.hydra_collection_base_schema_all_of_view import HydraCollectionBaseSchemaAllOfView
from gec_api_sdk.models.hydra_collection_base_schema_no_pagination_search import HydraCollectionBaseSchemaNoPaginationSearch
from gec_api_sdk.models.user_jsonld_user_read import UserJsonldUserRead
from typing import Optional, Set
from typing_extensions import Self

class ApiUsersGetCollection200Response(BaseModel):
    """
    User.jsonld-user.read collection.
    """ # noqa: E501
    total_items: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="totalItems")
    search: Optional[HydraCollectionBaseSchemaNoPaginationSearch] = None
    view: Optional[HydraCollectionBaseSchemaAllOfView] = None
    member: List[UserJsonldUserRead]
    __properties: ClassVar[List[str]] = ["totalItems", "search", "view", "member"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiUsersGetCollection200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of search
        if self.search:
            _dict['search'] = self.search.to_dict()
        # override the default output from pydantic by calling `to_dict()` of view
        if self.view:
            _dict['view'] = self.view.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in member (list)
        _items = []
        if self.member:
            for _item_member in self.member:
                if _item_member:
                    _items.append(_item_member.to_dict())
            _dict['member'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiUsersGetCollection200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in ApiUsersGetCollection200Response) in the input: " + _key)

        _obj = cls.model_validate({
            "totalItems": obj.get("totalItems"),
            "search": HydraCollectionBaseSchemaNoPaginationSearch.from_dict(obj["search"]) if obj.get("search") is not None else None,
            "view": HydraCollectionBaseSchemaAllOfView.from_dict(obj["view"]) if obj.get("view") is not None else None,
            "member": [UserJsonldUserRead.from_dict(_item) for _item in obj["member"]] if obj.get("member") is not None else None
        })
        return _obj


