# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DocumentDocumentRead(BaseModel):
    """
    DocumentDocumentRead
    """ # noqa: E501
    id: Optional[StrictStr] = None
    member: Optional[StrictStr] = None
    url: StrictStr
    type: Optional[StrictStr]
    uploaded_at: Optional[datetime] = Field(default=None, alias="uploadedAt")
    expires_at: Optional[datetime] = Field(default=None, alias="expiresAt")
    verified: Optional[StrictBool] = False
    verified_at: Optional[datetime] = Field(default=None, alias="verifiedAt")
    __properties: ClassVar[List[str]] = ["id", "member", "url", "type", "uploadedAt", "expiresAt", "verified", "verifiedAt"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['passport', 'visa', 'school_certificate', 'payment_receipt', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('passport', 'visa', 'school_certificate', 'payment_receipt', 'unknown_default_open_api')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocumentDocumentRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "uploaded_at",
            "verified_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expiresAt'] = None

        # set to None if verified_at (nullable) is None
        # and model_fields_set contains the field
        if self.verified_at is None and "verified_at" in self.model_fields_set:
            _dict['verifiedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocumentDocumentRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in DocumentDocumentRead) in the input: " + _key)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "member": obj.get("member"),
            "url": obj.get("url"),
            "type": obj.get("type"),
            "uploadedAt": obj.get("uploadedAt"),
            "expiresAt": obj.get("expiresAt"),
            "verified": obj.get("verified") if obj.get("verified") is not None else False,
            "verifiedAt": obj.get("verifiedAt")
        })
        return _obj


