# coding: utf-8

"""
    GEC API

    Backend API for the GEC (Gestion des Étudiants Congolais) non-profit management application. Provides endpoints for managing members, events, tasks, donations, and communications.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from gec_api_sdk.models.hello_asso_custom_field_dto import HelloAssoCustomFieldDTO
from typing import Optional, Set
from typing_extensions import Self

class HelloAssoItemDTO(BaseModel):
    """
    HelloAssoItemDTO
    """ # noqa: E501
    payments: Annotated[List[Optional[StrictStr]], Field(min_length=1)]
    name: StrictStr
    user: Optional[List[Optional[StrictStr]]] = None
    price_category: StrictStr = Field(alias="priceCategory")
    custom_fields: List[HelloAssoCustomFieldDTO] = Field(alias="customFields")
    qr_code: Optional[StrictStr] = Field(default=None, alias="qrCode")
    tier_description: Optional[StrictStr] = Field(default=None, alias="tierDescription")
    tier_id: Optional[StrictInt] = Field(default=None, alias="tierId")
    id: Annotated[int, Field(strict=True, ge=0)]
    amount: Annotated[int, Field(strict=True, ge=0)]
    type: StrictStr
    initial_amount: Annotated[int, Field(strict=True, ge=0)] = Field(alias="initialAmount")
    state: StrictStr
    __properties: ClassVar[List[str]] = ["payments", "name", "user", "priceCategory", "customFields", "qrCode", "tierDescription", "tierId", "id", "amount", "type", "initialAmount", "state"]

    @field_validator('price_category')
    def price_category_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Fixed', 'Variable', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('Fixed', 'Variable', 'unknown_default_open_api')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Membership', 'Donation', 'Event', 'Crowdfunding', 'Checkout', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('Membership', 'Donation', 'Event', 'Crowdfunding', 'Checkout', 'unknown_default_open_api')")
        return value

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Processed', 'Pending', 'Canceled', 'Refunded', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('Processed', 'Pending', 'Canceled', 'Refunded', 'unknown_default_open_api')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HelloAssoItemDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in custom_fields (list)
        _items = []
        if self.custom_fields:
            for _item_custom_fields in self.custom_fields:
                if _item_custom_fields:
                    _items.append(_item_custom_fields.to_dict())
            _dict['customFields'] = _items
        # set to None if user (nullable) is None
        # and model_fields_set contains the field
        if self.user is None and "user" in self.model_fields_set:
            _dict['user'] = None

        # set to None if qr_code (nullable) is None
        # and model_fields_set contains the field
        if self.qr_code is None and "qr_code" in self.model_fields_set:
            _dict['qrCode'] = None

        # set to None if tier_description (nullable) is None
        # and model_fields_set contains the field
        if self.tier_description is None and "tier_description" in self.model_fields_set:
            _dict['tierDescription'] = None

        # set to None if tier_id (nullable) is None
        # and model_fields_set contains the field
        if self.tier_id is None and "tier_id" in self.model_fields_set:
            _dict['tierId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HelloAssoItemDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in HelloAssoItemDTO) in the input: " + _key)

        _obj = cls.model_validate({
            "payments": obj.get("payments"),
            "name": obj.get("name"),
            "user": obj.get("user"),
            "priceCategory": obj.get("priceCategory"),
            "customFields": [HelloAssoCustomFieldDTO.from_dict(_item) for _item in obj["customFields"]] if obj.get("customFields") is not None else None,
            "qrCode": obj.get("qrCode"),
            "tierDescription": obj.get("tierDescription"),
            "tierId": obj.get("tierId"),
            "id": obj.get("id"),
            "amount": obj.get("amount"),
            "type": obj.get("type"),
            "initialAmount": obj.get("initialAmount"),
            "state": obj.get("state")
        })
        return _obj


