# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from gec_api_sdk.models.constraint_violation_jsonld_jsonld_context import ConstraintViolationJsonldJsonldContext
from typing import Optional, Set
from typing_extensions import Self

class MemberJsonldMemberRead(BaseModel):
    """
    
    """ # noqa: E501
    context: Optional[ConstraintViolationJsonldJsonldContext] = Field(default=None, alias="@context")
    id: Optional[StrictStr] = Field(default=None, alias="@id")
    type: Optional[StrictStr] = Field(default=None, alias="@type")
    id: Optional[StrictStr] = None
    first_name: StrictStr = Field(alias="firstName")
    last_name: StrictStr = Field(alias="lastName")
    email: StrictStr
    birth_date: Optional[datetime] = Field(default=None, alias="birthDate")
    gender: Optional[StrictStr] = None
    phone_number_fr: Optional[StrictStr] = Field(default=None, alias="phoneNumberFr")
    phone_number_cg: Optional[StrictStr] = Field(default=None, alias="phoneNumberCg")
    postal_address: Optional[StrictStr] = Field(default=None, alias="postalAddress")
    postal_code: Optional[StrictStr] = Field(default=None, alias="postalCode")
    city: Optional[StrictStr] = None
    first_year: Optional[StrictBool] = Field(default=None, alias="firstYear")
    formation: Optional[StrictStr] = None
    establishment: Optional[StrictStr] = None
    study_level: Optional[StrictStr] = Field(default=None, alias="studyLevel")
    training_cycle: Optional[StrictStr] = Field(default=None, alias="trainingCycle")
    other_associations: Optional[StrictBool] = Field(default=None, alias="otherAssociations")
    association_names: Optional[StrictStr] = Field(default=None, alias="associationNames")
    has_passport_cg: Optional[StrictBool] = Field(default=None, alias="hasPassportCg")
    has_visa: Optional[StrictBool] = Field(default=None, alias="hasVisa")
    has_school_certificate: Optional[StrictBool] = Field(default=None, alias="hasSchoolCertificate")
    photo_url: Optional[StrictStr] = Field(default=None, alias="photoUrl")
    status: StrictStr
    membership_type: StrictStr = Field(alias="membershipType")
    contribution: Optional[StrictStr] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    documents: Optional[List[StrictStr]] = None
    rsvps: Optional[List[StrictStr]] = None
    donations: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["@context", "@id", "@type", "id", "firstName", "lastName", "email", "birthDate", "gender", "phoneNumberFr", "phoneNumberCg", "postalAddress", "postalCode", "city", "firstYear", "formation", "establishment", "studyLevel", "trainingCycle", "otherAssociations", "associationNames", "hasPassportCg", "hasVisa", "hasSchoolCertificate", "photoUrl", "status", "membershipType", "contribution", "createdAt", "updatedAt", "documents", "rsvps", "donations"]

    @field_validator('gender')
    def gender_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['male', 'female', 'other', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('male', 'female', 'other', 'unknown_default_open_api')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['active', 'pending', 'expired', 'suspended', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('active', 'pending', 'expired', 'suspended', 'unknown_default_open_api')")
        return value

    @field_validator('membership_type')
    def membership_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['student', 'active', 'sponsor', 'alumni', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('student', 'active', 'sponsor', 'alumni', 'unknown_default_open_api')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MemberJsonldMemberRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "type",
            "id",
            "created_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of context
        if self.context:
            _dict['@context'] = self.context.to_dict()
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if birth_date (nullable) is None
        # and model_fields_set contains the field
        if self.birth_date is None and "birth_date" in self.model_fields_set:
            _dict['birthDate'] = None

        # set to None if gender (nullable) is None
        # and model_fields_set contains the field
        if self.gender is None and "gender" in self.model_fields_set:
            _dict['gender'] = None

        # set to None if phone_number_fr (nullable) is None
        # and model_fields_set contains the field
        if self.phone_number_fr is None and "phone_number_fr" in self.model_fields_set:
            _dict['phoneNumberFr'] = None

        # set to None if phone_number_cg (nullable) is None
        # and model_fields_set contains the field
        if self.phone_number_cg is None and "phone_number_cg" in self.model_fields_set:
            _dict['phoneNumberCg'] = None

        # set to None if postal_address (nullable) is None
        # and model_fields_set contains the field
        if self.postal_address is None and "postal_address" in self.model_fields_set:
            _dict['postalAddress'] = None

        # set to None if postal_code (nullable) is None
        # and model_fields_set contains the field
        if self.postal_code is None and "postal_code" in self.model_fields_set:
            _dict['postalCode'] = None

        # set to None if city (nullable) is None
        # and model_fields_set contains the field
        if self.city is None and "city" in self.model_fields_set:
            _dict['city'] = None

        # set to None if first_year (nullable) is None
        # and model_fields_set contains the field
        if self.first_year is None and "first_year" in self.model_fields_set:
            _dict['firstYear'] = None

        # set to None if formation (nullable) is None
        # and model_fields_set contains the field
        if self.formation is None and "formation" in self.model_fields_set:
            _dict['formation'] = None

        # set to None if establishment (nullable) is None
        # and model_fields_set contains the field
        if self.establishment is None and "establishment" in self.model_fields_set:
            _dict['establishment'] = None

        # set to None if study_level (nullable) is None
        # and model_fields_set contains the field
        if self.study_level is None and "study_level" in self.model_fields_set:
            _dict['studyLevel'] = None

        # set to None if training_cycle (nullable) is None
        # and model_fields_set contains the field
        if self.training_cycle is None and "training_cycle" in self.model_fields_set:
            _dict['trainingCycle'] = None

        # set to None if other_associations (nullable) is None
        # and model_fields_set contains the field
        if self.other_associations is None and "other_associations" in self.model_fields_set:
            _dict['otherAssociations'] = None

        # set to None if association_names (nullable) is None
        # and model_fields_set contains the field
        if self.association_names is None and "association_names" in self.model_fields_set:
            _dict['associationNames'] = None

        # set to None if has_passport_cg (nullable) is None
        # and model_fields_set contains the field
        if self.has_passport_cg is None and "has_passport_cg" in self.model_fields_set:
            _dict['hasPassportCg'] = None

        # set to None if has_visa (nullable) is None
        # and model_fields_set contains the field
        if self.has_visa is None and "has_visa" in self.model_fields_set:
            _dict['hasVisa'] = None

        # set to None if has_school_certificate (nullable) is None
        # and model_fields_set contains the field
        if self.has_school_certificate is None and "has_school_certificate" in self.model_fields_set:
            _dict['hasSchoolCertificate'] = None

        # set to None if photo_url (nullable) is None
        # and model_fields_set contains the field
        if self.photo_url is None and "photo_url" in self.model_fields_set:
            _dict['photoUrl'] = None

        # set to None if contribution (nullable) is None
        # and model_fields_set contains the field
        if self.contribution is None and "contribution" in self.model_fields_set:
            _dict['contribution'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MemberJsonldMemberRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in MemberJsonldMemberRead) in the input: " + _key)

        _obj = cls.model_validate({
            "@context": ConstraintViolationJsonldJsonldContext.from_dict(obj["@context"]) if obj.get("@context") is not None else None,
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "id": obj.get("id"),
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "email": obj.get("email"),
            "birthDate": obj.get("birthDate"),
            "gender": obj.get("gender"),
            "phoneNumberFr": obj.get("phoneNumberFr"),
            "phoneNumberCg": obj.get("phoneNumberCg"),
            "postalAddress": obj.get("postalAddress"),
            "postalCode": obj.get("postalCode"),
            "city": obj.get("city"),
            "firstYear": obj.get("firstYear"),
            "formation": obj.get("formation"),
            "establishment": obj.get("establishment"),
            "studyLevel": obj.get("studyLevel"),
            "trainingCycle": obj.get("trainingCycle"),
            "otherAssociations": obj.get("otherAssociations"),
            "associationNames": obj.get("associationNames"),
            "hasPassportCg": obj.get("hasPassportCg"),
            "hasVisa": obj.get("hasVisa"),
            "hasSchoolCertificate": obj.get("hasSchoolCertificate"),
            "photoUrl": obj.get("photoUrl"),
            "status": obj.get("status"),
            "membershipType": obj.get("membershipType"),
            "contribution": obj.get("contribution"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "documents": obj.get("documents"),
            "rsvps": obj.get("rsvps"),
            "donations": obj.get("donations")
        })
        return _obj


