# coding: utf-8

"""
    GEC API

    Backend API for the GEC (Gestion des Étudiants Congolais) non-profit management application. Provides endpoints for managing members, events, tasks, donations, and communications.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class MemberWrite(BaseModel):
    """
    MemberWrite
    """ # noqa: E501
    first_name: StrictStr = Field(description="Member's first name.", alias="firstName")
    last_name: StrictStr = Field(description="Member's last name.", alias="lastName")
    email: Optional[StrictStr] = Field(default=None, description="Unique email address.")
    birth_date: Optional[date] = Field(default=None, description="Date of birth.", alias="birthDate")
    gender: Optional[StrictStr] = Field(default=None, description="Gender.")
    phone_number_fr: Optional[StrictStr] = Field(default=None, description="French phone number.", alias="phoneNumberFr")
    phone_number_cg: Optional[StrictStr] = Field(default=None, description="Congolese phone number.", alias="phoneNumberCg")
    postal_address: Optional[StrictStr] = Field(default=None, description="Street address.", alias="postalAddress")
    postal_code: Optional[StrictStr] = Field(default=None, description="Postal/zip code.", alias="postalCode")
    city: Optional[StrictStr] = Field(default=None, description="City of residence.")
    is_first_year_study: Optional[StrictBool] = Field(default=None, description="Whether this is the member's first year of study.", alias="isFirstYearStudy")
    first_year: Optional[date] = Field(default=None, description="Start date of the first year of study.", alias="firstYear")
    formation: Optional[StrictStr] = Field(default=None, description="Field of study / training programme.")
    establishment: Optional[StrictStr] = Field(default=None, description="Educational establishment (school or university).")
    study_level: Optional[StrictStr] = Field(default=None, description="Current study level (e.g. Licence 1, Master 2).", alias="studyLevel")
    training_cycle: Optional[StrictStr] = Field(default=None, description="Training cycle: initial, apprenticeship, or continuing education.", alias="trainingCycle")
    other_associations: Optional[StrictBool] = Field(default=None, description="Whether the member belongs to other associations.", alias="otherAssociations")
    association_names: Optional[StrictStr] = Field(default=None, description="Names of other associations the member belongs to.", alias="associationNames")
    has_passport_cg: Optional[StrictBool] = Field(default=None, description="Whether the member holds a Congolese passport.", alias="hasPassportCg")
    has_visa: Optional[StrictBool] = Field(default=None, description="Whether the member holds a valid visa.", alias="hasVisa")
    has_school_certificate: Optional[StrictBool] = Field(default=None, description="Whether the member has provided a school certificate.", alias="hasSchoolCertificate")
    photo_url: Optional[StrictStr] = Field(default=None, description="URL of the member's profile photo.", alias="photoUrl")
    status: Optional[StrictStr] = Field(description="Membership status: active, pending, expired, or suspended.")
    membership_type: Optional[StrictStr] = Field(description="Membership type: student, active, sponsor, or alumni.", alias="membershipType")
    membership_start_date: Optional[date] = Field(default=None, description="Date when the current membership period started.", alias="membershipStartDate")
    contribution: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Membership fee amount paid (in euros).")
    contribution_status: Optional[StrictStr] = Field(default=None, description="Contribution payment status: paid, pending, or expired.", alias="contributionStatus")
    __properties: ClassVar[List[str]] = ["firstName", "lastName", "email", "birthDate", "gender", "phoneNumberFr", "phoneNumberCg", "postalAddress", "postalCode", "city", "isFirstYearStudy", "firstYear", "formation", "establishment", "studyLevel", "trainingCycle", "otherAssociations", "associationNames", "hasPassportCg", "hasVisa", "hasSchoolCertificate", "photoUrl", "status", "membershipType", "membershipStartDate", "contribution", "contributionStatus"]

    @field_validator('gender')
    def gender_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['male', 'female', 'other', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('male', 'female', 'other', 'unknown_default_open_api')")
        return value

    @field_validator('training_cycle')
    def training_cycle_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['initial', 'apprenticeship', 'continuing_education', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('initial', 'apprenticeship', 'continuing_education', 'unknown_default_open_api')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['active', 'pending', 'expired', 'suspended', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('active', 'pending', 'expired', 'suspended', 'unknown_default_open_api')")
        return value

    @field_validator('membership_type')
    def membership_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['student', 'active', 'sponsor', 'alumni', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('student', 'active', 'sponsor', 'alumni', 'unknown_default_open_api')")
        return value

    @field_validator('contribution_status')
    def contribution_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['paid', 'pending', 'expired', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('paid', 'pending', 'expired', 'unknown_default_open_api')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MemberWrite from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if birth_date (nullable) is None
        # and model_fields_set contains the field
        if self.birth_date is None and "birth_date" in self.model_fields_set:
            _dict['birthDate'] = None

        # set to None if gender (nullable) is None
        # and model_fields_set contains the field
        if self.gender is None and "gender" in self.model_fields_set:
            _dict['gender'] = None

        # set to None if phone_number_fr (nullable) is None
        # and model_fields_set contains the field
        if self.phone_number_fr is None and "phone_number_fr" in self.model_fields_set:
            _dict['phoneNumberFr'] = None

        # set to None if phone_number_cg (nullable) is None
        # and model_fields_set contains the field
        if self.phone_number_cg is None and "phone_number_cg" in self.model_fields_set:
            _dict['phoneNumberCg'] = None

        # set to None if postal_address (nullable) is None
        # and model_fields_set contains the field
        if self.postal_address is None and "postal_address" in self.model_fields_set:
            _dict['postalAddress'] = None

        # set to None if postal_code (nullable) is None
        # and model_fields_set contains the field
        if self.postal_code is None and "postal_code" in self.model_fields_set:
            _dict['postalCode'] = None

        # set to None if city (nullable) is None
        # and model_fields_set contains the field
        if self.city is None and "city" in self.model_fields_set:
            _dict['city'] = None

        # set to None if is_first_year_study (nullable) is None
        # and model_fields_set contains the field
        if self.is_first_year_study is None and "is_first_year_study" in self.model_fields_set:
            _dict['isFirstYearStudy'] = None

        # set to None if first_year (nullable) is None
        # and model_fields_set contains the field
        if self.first_year is None and "first_year" in self.model_fields_set:
            _dict['firstYear'] = None

        # set to None if formation (nullable) is None
        # and model_fields_set contains the field
        if self.formation is None and "formation" in self.model_fields_set:
            _dict['formation'] = None

        # set to None if establishment (nullable) is None
        # and model_fields_set contains the field
        if self.establishment is None and "establishment" in self.model_fields_set:
            _dict['establishment'] = None

        # set to None if study_level (nullable) is None
        # and model_fields_set contains the field
        if self.study_level is None and "study_level" in self.model_fields_set:
            _dict['studyLevel'] = None

        # set to None if training_cycle (nullable) is None
        # and model_fields_set contains the field
        if self.training_cycle is None and "training_cycle" in self.model_fields_set:
            _dict['trainingCycle'] = None

        # set to None if other_associations (nullable) is None
        # and model_fields_set contains the field
        if self.other_associations is None and "other_associations" in self.model_fields_set:
            _dict['otherAssociations'] = None

        # set to None if association_names (nullable) is None
        # and model_fields_set contains the field
        if self.association_names is None and "association_names" in self.model_fields_set:
            _dict['associationNames'] = None

        # set to None if has_passport_cg (nullable) is None
        # and model_fields_set contains the field
        if self.has_passport_cg is None and "has_passport_cg" in self.model_fields_set:
            _dict['hasPassportCg'] = None

        # set to None if has_visa (nullable) is None
        # and model_fields_set contains the field
        if self.has_visa is None and "has_visa" in self.model_fields_set:
            _dict['hasVisa'] = None

        # set to None if has_school_certificate (nullable) is None
        # and model_fields_set contains the field
        if self.has_school_certificate is None and "has_school_certificate" in self.model_fields_set:
            _dict['hasSchoolCertificate'] = None

        # set to None if photo_url (nullable) is None
        # and model_fields_set contains the field
        if self.photo_url is None and "photo_url" in self.model_fields_set:
            _dict['photoUrl'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if membership_type (nullable) is None
        # and model_fields_set contains the field
        if self.membership_type is None and "membership_type" in self.model_fields_set:
            _dict['membershipType'] = None

        # set to None if membership_start_date (nullable) is None
        # and model_fields_set contains the field
        if self.membership_start_date is None and "membership_start_date" in self.model_fields_set:
            _dict['membershipStartDate'] = None

        # set to None if contribution (nullable) is None
        # and model_fields_set contains the field
        if self.contribution is None and "contribution" in self.model_fields_set:
            _dict['contribution'] = None

        # set to None if contribution_status (nullable) is None
        # and model_fields_set contains the field
        if self.contribution_status is None and "contribution_status" in self.model_fields_set:
            _dict['contributionStatus'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MemberWrite from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in MemberWrite) in the input: " + _key)

        _obj = cls.model_validate({
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "email": obj.get("email"),
            "birthDate": obj.get("birthDate"),
            "gender": obj.get("gender"),
            "phoneNumberFr": obj.get("phoneNumberFr"),
            "phoneNumberCg": obj.get("phoneNumberCg"),
            "postalAddress": obj.get("postalAddress"),
            "postalCode": obj.get("postalCode"),
            "city": obj.get("city"),
            "isFirstYearStudy": obj.get("isFirstYearStudy"),
            "firstYear": obj.get("firstYear"),
            "formation": obj.get("formation"),
            "establishment": obj.get("establishment"),
            "studyLevel": obj.get("studyLevel"),
            "trainingCycle": obj.get("trainingCycle"),
            "otherAssociations": obj.get("otherAssociations"),
            "associationNames": obj.get("associationNames"),
            "hasPassportCg": obj.get("hasPassportCg"),
            "hasVisa": obj.get("hasVisa"),
            "hasSchoolCertificate": obj.get("hasSchoolCertificate"),
            "photoUrl": obj.get("photoUrl"),
            "status": obj.get("status"),
            "membershipType": obj.get("membershipType"),
            "membershipStartDate": obj.get("membershipStartDate"),
            "contribution": obj.get("contribution"),
            "contributionStatus": obj.get("contributionStatus")
        })
        return _obj


