# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from gec_api_sdk.models.hydra_item_base_schema_context import HydraItemBaseSchemaContext
from typing import Optional, Set
from typing_extensions import Self

class TaskJsonldTaskRead(BaseModel):
    """
    TaskJsonldTaskRead
    """ # noqa: E501
    context: Optional[HydraItemBaseSchemaContext] = Field(default=None, alias="@context")
    id: StrictStr = Field(alias="@id")
    type: StrictStr = Field(alias="@type")
    id: Optional[StrictStr] = None
    title: StrictStr
    description: Optional[StrictStr] = None
    status: Optional[StrictStr] = 'pending'
    assignee: Optional[StrictStr] = None
    due_date: Optional[datetime] = Field(default=None, alias="dueDate")
    priority: Optional[StrictStr] = None
    related_event: Optional[StrictStr] = Field(default=None, alias="relatedEvent")
    related_member: Optional[StrictStr] = Field(default=None, alias="relatedMember")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    __properties: ClassVar[List[str]] = ["@context", "@id", "@type", "id", "title", "description", "status", "assignee", "dueDate", "priority", "relatedEvent", "relatedMember", "createdAt", "updatedAt"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending', 'in_progress', 'completed', 'cancelled', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('pending', 'in_progress', 'completed', 'cancelled', 'unknown_default_open_api')")
        return value

    @field_validator('priority')
    def priority_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['low', 'medium', 'high', 'unknown_default_open_api']):
            raise ValueError("must be one of enum values ('low', 'medium', 'high', 'unknown_default_open_api')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaskJsonldTaskRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "created_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of context
        if self.context:
            _dict['@context'] = self.context.to_dict()
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if assignee (nullable) is None
        # and model_fields_set contains the field
        if self.assignee is None and "assignee" in self.model_fields_set:
            _dict['assignee'] = None

        # set to None if due_date (nullable) is None
        # and model_fields_set contains the field
        if self.due_date is None and "due_date" in self.model_fields_set:
            _dict['dueDate'] = None

        # set to None if priority (nullable) is None
        # and model_fields_set contains the field
        if self.priority is None and "priority" in self.model_fields_set:
            _dict['priority'] = None

        # set to None if related_event (nullable) is None
        # and model_fields_set contains the field
        if self.related_event is None and "related_event" in self.model_fields_set:
            _dict['relatedEvent'] = None

        # set to None if related_member (nullable) is None
        # and model_fields_set contains the field
        if self.related_member is None and "related_member" in self.model_fields_set:
            _dict['relatedMember'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaskJsonldTaskRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in TaskJsonldTaskRead) in the input: " + _key)

        _obj = cls.model_validate({
            "@context": HydraItemBaseSchemaContext.from_dict(obj["@context"]) if obj.get("@context") is not None else None,
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "id": obj.get("id"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "status": obj.get("status") if obj.get("status") is not None else 'pending',
            "assignee": obj.get("assignee"),
            "dueDate": obj.get("dueDate"),
            "priority": obj.get("priority"),
            "relatedEvent": obj.get("relatedEvent"),
            "relatedMember": obj.get("relatedMember"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


