# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gec_api_sdk.models.hydra_item_base_schema_context import HydraItemBaseSchemaContext
from typing import Optional, Set
from typing_extensions import Self

class UserJsonldUserRead(BaseModel):
    """
    UserJsonldUserRead
    """ # noqa: E501
    context: Optional[HydraItemBaseSchemaContext] = Field(default=None, alias="@context")
    id: StrictStr = Field(alias="@id")
    type: StrictStr = Field(alias="@type")
    id: Optional[StrictStr] = None
    email: StrictStr
    roles: Optional[List[StrictStr]] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    google_service_account: Optional[StrictStr] = Field(default=None, alias="googleServiceAccount")
    google_service_account_scopes: Optional[List[Optional[StrictStr]]] = Field(default=None, alias="googleServiceAccountScopes")
    google_impersonated_user: Optional[StrictStr] = Field(default=None, alias="googleImpersonatedUser")
    __properties: ClassVar[List[str]] = ["@context", "@id", "@type", "id", "email", "roles", "createdAt", "updatedAt", "googleServiceAccount", "googleServiceAccountScopes", "googleImpersonatedUser"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserJsonldUserRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "created_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of context
        if self.context:
            _dict['@context'] = self.context.to_dict()
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if google_service_account (nullable) is None
        # and model_fields_set contains the field
        if self.google_service_account is None and "google_service_account" in self.model_fields_set:
            _dict['googleServiceAccount'] = None

        # set to None if google_service_account_scopes (nullable) is None
        # and model_fields_set contains the field
        if self.google_service_account_scopes is None and "google_service_account_scopes" in self.model_fields_set:
            _dict['googleServiceAccountScopes'] = None

        # set to None if google_impersonated_user (nullable) is None
        # and model_fields_set contains the field
        if self.google_impersonated_user is None and "google_impersonated_user" in self.model_fields_set:
            _dict['googleImpersonatedUser'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserJsonldUserRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in UserJsonldUserRead) in the input: " + _key)

        _obj = cls.model_validate({
            "@context": HydraItemBaseSchemaContext.from_dict(obj["@context"]) if obj.get("@context") is not None else None,
            "@id": obj.get("@id"),
            "@type": obj.get("@type"),
            "id": obj.get("id"),
            "email": obj.get("email"),
            "roles": obj.get("roles"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "googleServiceAccount": obj.get("googleServiceAccount"),
            "googleServiceAccountScopes": obj.get("googleServiceAccountScopes"),
            "googleImpersonatedUser": obj.get("googleImpersonatedUser")
        })
        return _obj


