# coding: utf-8

"""
    GEC API

    Backend API for the GEC (Gestion des Étudiants Congolais) non-profit management application. Provides endpoints for managing members, events, tasks, donations, and communications.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO(BaseModel):
    """
    DTO for WIF credential token API endpoint.  This DTO acts as both the API Platform resource definition and the response format. It follows the HelloAssoWebhookDTO pattern where the DTO defines the API endpoint and the processor handles the business logic.  Unlike HelloAsso which returns a Member entity, this endpoint returns a credential response with a JWT token, which is better represented as a DTO rather than an entity since we don't persist credential tokens.  Security Features (enforced via processor): - Rate limiting per IP and user (A07: Authentication Failures) - Input validation and sanitization (A03: Injection) - Comprehensive audit logging (A09: Security Logging) - IP allowlist support (A01: Broken Access Control) - Protection against timing attacks
    """ # noqa: E501
    user_email: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    service_account: Optional[Annotated[str, Field(strict=True, max_length=512)]] = None
    ttl: Optional[Annotated[int, Field(le=86400, strict=True, ge=0)]] = None
    __properties: ClassVar[List[str]] = ["user_email", "service_account", "ttl"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if user_email (nullable) is None
        # and model_fields_set contains the field
        if self.user_email is None and "user_email" in self.model_fields_set:
            _dict['user_email'] = None

        # set to None if service_account (nullable) is None
        # and model_fields_set contains the field
        if self.service_account is None and "service_account" in self.model_fields_set:
            _dict['service_account'] = None

        # set to None if ttl (nullable) is None
        # and model_fields_set contains the field
        if self.ttl is None and "ttl" in self.model_fields_set:
            _dict['ttl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO) in the input: " + _key)

        _obj = cls.model_validate({
            "user_email": obj.get("user_email"),
            "service_account": obj.get("service_account"),
            "ttl": obj.get("ttl")
        })
        return _obj


