# coding: utf-8

"""
    GEC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WifCredentialTokenResponseDTO(BaseModel):
    """
    DTO for WIF credential token API endpoint.  This DTO acts as both the API Platform resource definition and the response format. It follows the HelloAssoWebhookDTO pattern where the DTO defines the API endpoint and the processor handles the business logic.  Unlike HelloAsso which returns a Member entity, this endpoint returns a credential response with a JWT token, which is better represented as a DTO rather than an entity since we don't persist credential tokens.  Security Features (enforced via processor): - Rate limiting per IP and user (A07: Authentication Failures) - Input validation and sanitization (A03: Injection) - Comprehensive audit logging (A09: Security Logging) - IP allowlist support (A01: Broken Access Control) - Protection against timing attacks
    """ # noqa: E501
    version: Optional[StrictInt] = None
    success: Optional[StrictBool] = None
    token_type: Optional[StrictStr] = None
    expires_in: Optional[StrictInt] = None
    expiration_time: Optional[StrictInt] = None
    access_token: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["version", "success", "token_type", "expires_in", "expiration_time", "access_token"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WifCredentialTokenResponseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if token_type (nullable) is None
        # and model_fields_set contains the field
        if self.token_type is None and "token_type" in self.model_fields_set:
            _dict['token_type'] = None

        # set to None if expires_in (nullable) is None
        # and model_fields_set contains the field
        if self.expires_in is None and "expires_in" in self.model_fields_set:
            _dict['expires_in'] = None

        # set to None if expiration_time (nullable) is None
        # and model_fields_set contains the field
        if self.expiration_time is None and "expiration_time" in self.model_fields_set:
            _dict['expiration_time'] = None

        # set to None if access_token (nullable) is None
        # and model_fields_set contains the field
        if self.access_token is None and "access_token" in self.model_fields_set:
            _dict['access_token'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WifCredentialTokenResponseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in WifCredentialTokenResponseDTO) in the input: " + _key)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "success": obj.get("success"),
            "token_type": obj.get("token_type"),
            "expires_in": obj.get("expires_in"),
            "expiration_time": obj.get("expiration_time"),
            "access_token": obj.get("access_token")
        })
        return _obj


