# coding: utf-8

# flake8: noqa

"""
    GEC API

    Backend API for the GEC (Gestion des Étudiants Congolais) non-profit management application. Provides endpoints for managing members, events, tasks, donations, and communications.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "DocumentApi",
    "DonationApi",
    "EmailTemplateApi",
    "EventApi",
    "LoginCheckApi",
    "MemberApi",
    "RsvpApi",
    "TaskApi",
    "UserApi",
    "WifCredentialTokenResponseDTOApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ConstraintViolation",
    "ConstraintViolationViolationsInner",
    "DocumentRead",
    "DocumentWrite",
    "DonationRead",
    "DonationWrite",
    "EmailTemplateRead",
    "EmailTemplateWrite",
    "Error",
    "EventRead",
    "EventWrite",
    "LoginCheckPost200Response",
    "LoginCheckPostRequest",
    "MemberRead",
    "MemberWrite",
    "RsvpRead",
    "RsvpWrite",
    "TaskRead",
    "TaskWrite",
    "UserRead",
    "UserWrite",
    "WifCredentialTokenResponseDTO",
    "WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO",
]

# import apis into sdk package
from gec_api_sdk.api.document_api import DocumentApi as DocumentApi
from gec_api_sdk.api.donation_api import DonationApi as DonationApi
from gec_api_sdk.api.email_template_api import EmailTemplateApi as EmailTemplateApi
from gec_api_sdk.api.event_api import EventApi as EventApi
from gec_api_sdk.api.login_check_api import LoginCheckApi as LoginCheckApi
from gec_api_sdk.api.member_api import MemberApi as MemberApi
from gec_api_sdk.api.rsvp_api import RsvpApi as RsvpApi
from gec_api_sdk.api.task_api import TaskApi as TaskApi
from gec_api_sdk.api.user_api import UserApi as UserApi
from gec_api_sdk.api.wif_credential_token_response_dto_api import WifCredentialTokenResponseDTOApi as WifCredentialTokenResponseDTOApi

# import ApiClient
from gec_api_sdk.api_response import ApiResponse as ApiResponse
from gec_api_sdk.api_client import ApiClient as ApiClient
from gec_api_sdk.configuration import Configuration as Configuration
from gec_api_sdk.exceptions import OpenApiException as OpenApiException
from gec_api_sdk.exceptions import ApiTypeError as ApiTypeError
from gec_api_sdk.exceptions import ApiValueError as ApiValueError
from gec_api_sdk.exceptions import ApiKeyError as ApiKeyError
from gec_api_sdk.exceptions import ApiAttributeError as ApiAttributeError
from gec_api_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from gec_api_sdk.models.constraint_violation import ConstraintViolation as ConstraintViolation
from gec_api_sdk.models.constraint_violation_violations_inner import ConstraintViolationViolationsInner as ConstraintViolationViolationsInner
from gec_api_sdk.models.document_read import DocumentRead as DocumentRead
from gec_api_sdk.models.document_write import DocumentWrite as DocumentWrite
from gec_api_sdk.models.donation_read import DonationRead as DonationRead
from gec_api_sdk.models.donation_write import DonationWrite as DonationWrite
from gec_api_sdk.models.email_template_read import EmailTemplateRead as EmailTemplateRead
from gec_api_sdk.models.email_template_write import EmailTemplateWrite as EmailTemplateWrite
from gec_api_sdk.models.error import Error as Error
from gec_api_sdk.models.event_read import EventRead as EventRead
from gec_api_sdk.models.event_write import EventWrite as EventWrite
from gec_api_sdk.models.login_check_post200_response import LoginCheckPost200Response as LoginCheckPost200Response
from gec_api_sdk.models.login_check_post_request import LoginCheckPostRequest as LoginCheckPostRequest
from gec_api_sdk.models.member_read import MemberRead as MemberRead
from gec_api_sdk.models.member_write import MemberWrite as MemberWrite
from gec_api_sdk.models.rsvp_read import RsvpRead as RsvpRead
from gec_api_sdk.models.rsvp_write import RsvpWrite as RsvpWrite
from gec_api_sdk.models.task_read import TaskRead as TaskRead
from gec_api_sdk.models.task_write import TaskWrite as TaskWrite
from gec_api_sdk.models.user_read import UserRead as UserRead
from gec_api_sdk.models.user_write import UserWrite as UserWrite
from gec_api_sdk.models.wif_credential_token_response_dto import WifCredentialTokenResponseDTO as WifCredentialTokenResponseDTO
from gec_api_sdk.models.wif_credential_token_response_dto_wif_credential_token_request_dto import WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO as WifCredentialTokenResponseDTOWifCredentialTokenRequestDTO

